# Generated by Django 4.2.20 on 2025-05-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('status', models.IntegerField(choices=[(0, 'В приюте'), (1, 'Пристроен')], default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
                'ordering': ['-time_create'],
            },
        ),
    ]
