# Generated by Django 4.2.20 on 2025-05-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='animals/%Y/%m/%d/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.IntegerField(choices=[(0, 'В приюте'), (1, 'Пристроен')], default=0, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['status'], name='my_animals__status_bf02e5_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['breed'], name='my_animals__breed_8f386e_idx'),
        ),
    ]
