# Generated by Django 4.2.20 on 2025-05-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_animals', '0002_alter_animal_description_alter_animal_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, default='animals/default.jpg', null=True, upload_to='animals/', verbose_name='Фотография'),
        ),
    ]
